name: publish
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          version-type: beta
          modrinth-id: Ti4CmdHK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-dependencies: |
            fabric-api | depends | *

          curseforge-id: 635713
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-dependencies: |
            fabric-api | depends | *

          game-versions: |
            1.18.2

          loaders: |
            fabric

          changelog-file: CHANGELOG.md

          java: |
            17